name: Docker Image CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.10.0
    
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        push: true
        tags: abhinavrenjith/todo:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Deploy to Remote Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        # Create private key file
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        
        # SSH and deploy
        ssh -o StrictHostKeyChecking=no -p $SERVER_PORT -i private_key $SERVER_USER@$SERVER_IP << EOF
          # Docker login
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          
          # Pull the latest image
          docker pull abhinavrenjith/todo:latest
          
          # Stop and remove existing container
          docker stop todo_run || true
          docker rm todo_run || true
          
          # Run new container
          docker run -d --name todo_run -p 3336:3336 abhinavrenjith/todo:latest
          
          # Verify deployment
          sleep 5
          docker ps | grep todo_run
        EOF
