name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.10.0

    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER__PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        push: true
        tags: abhinavrenjith/todo:latest

    - name: Decode SSH private key
      run: |
        echo "${{ secrets.SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
     
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: 61002
        key_path: ~/.ssh/id_rsa
        script: |
          docker pull abhinavrenjith/todo:latest
          docker stop todo || true
          docker rm todo || true
          docker run -d --name todo_run -p 3336:3336 abhinavrenjith/todo:latest

