name: Docker Image CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.10.0
    
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        push: true
        tags: abhinavrenjith/todo:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Deploy to Remote Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          # Pull the latest image
          docker pull abhinavrenjith/todo:latest
          
          # Stop and remove existing container
          docker stop todo_run || true
          docker rm todo_run || true
          
          # Run new container
          docker run -d --name todo_run -p 3336:3336 abhinavrenjith/todo:latest
          
          # Verify deployment
          sleep 5
          docker ps | grep todo_run
