name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.10.0

    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER__PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        push: true
        tags: abhinavrenjith/todo:latest

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh_private_key
        chmod 600 /tmp/ssh_private_key

        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_private_key ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} '
        script: |
          docker pull abhinavrenjith/todo:latest
          docker stop todo || true
          docker rm todo || true
          docker run -d --name todo_run -p 3336:3336 abhinavrenjith/todo:latest
